# title = "Tomloc Localizations Example"

[hello]
en = "Hello World"
uk = "Привіт світ"

[bye_bye]
en = "Bye Bye"
uk = "Бувай"

[param]
en = "Hello, %{name}!"
uk = "Привіт, %{name}!"

[list]
en = ["one", "%{two}", "three"]
uk = ["один", "%{two}", "три"]

[array]
en = ["", "two", " ", "%{empty}"]
uk = ["", "два", " ", "%{empty}"]


